--------------------------------------------------------
--  File created - Tuesday-January-05-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APPOINTMENT
--------------------------------------------------------

  CREATE TABLE "MAHMOUD"."APPOINTMENT" 
   (	"ID" NUMBER, 
	"DATES" NUMBER, 
	"ID_APPOINTMENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONSULTATION
--------------------------------------------------------

  CREATE TABLE "MAHMOUD"."CONSULTATION" 
   (	"ID" NUMBER, 
	"DATES" NUMBER, 
	"WEIGHT" NUMBER, 
	"TEMPERATURE" NUMBER, 
	"PRESSURE" NUMBER, 
	"ID_CONSULTATION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "MAHMOUD"."DEPARTMENT" 
   (	"ID" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOGIN
--------------------------------------------------------

  CREATE TABLE "MAHMOUD"."LOGIN" 
   (	"MAIL" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDICALFILE
--------------------------------------------------------

  CREATE TABLE "MAHMOUD"."MEDICALFILE" 
   (	"ID" NUMBER, 
	"PRESSURE" NUMBER, 
	"LUNGS" VARCHAR2(20 BYTE), 
	"BLOOD_TYPE" VARCHAR2(20 BYTE), 
	"CHRONIC_DISEASES" VARCHAR2(20 BYTE), 
	"ID_MRECORD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEDICATIONS
--------------------------------------------------------

  CREATE TABLE "MAHMOUD"."MEDICATIONS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"DATES" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER, 
	"QUANTITY" NUMBER, 
	"ID_MEDICATION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PATIENT
--------------------------------------------------------

  CREATE TABLE "MAHMOUD"."PATIENT" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(20 BYTE), 
	"AGE" NUMBER, 
	"GENDER" VARCHAR2(20 BYTE), 
	"ID_PATIENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRESCRIPTION
--------------------------------------------------------

  CREATE TABLE "MAHMOUD"."PRESCRIPTION" 
   (	"ID" NUMBER, 
	"DATES" VARCHAR2(20 BYTE), 
	"DOSE" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"ID_PRESCREPTION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECRUITS
--------------------------------------------------------

  CREATE TABLE "MAHMOUD"."RECRUITS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"YEAR_OF_BIRTH" VARCHAR2(20 BYTE), 
	"SEX" VARCHAR2(20 BYTE), 
	"DEPARTMENT" VARCHAR2(20 BYTE), 
	"ID_RECRUITS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESULTS
--------------------------------------------------------

  CREATE TABLE "MAHMOUD"."RESULTS" 
   (	"ID" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"COVID19" VARCHAR2(20 BYTE), 
	"ID_RESULTS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TEST
--------------------------------------------------------

  CREATE TABLE "MAHMOUD"."TEST" 
   (	"ID" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"ID_TEST" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into MAHMOUD.APPOINTMENT
SET DEFINE OFF;
Insert into MAHMOUD.APPOINTMENT (ID,DATES,ID_APPOINTMENT) values (14,14,null);
REM INSERTING into MAHMOUD.CONSULTATION
SET DEFINE OFF;
Insert into MAHMOUD.CONSULTATION (ID,DATES,WEIGHT,TEMPERATURE,PRESSURE,ID_CONSULTATION) values (14,14,14,14,14,null);
REM INSERTING into MAHMOUD.DEPARTMENT
SET DEFINE OFF;
Insert into MAHMOUD.DEPARTMENT (ID,TYPE) values (1,'doctors');
Insert into MAHMOUD.DEPARTMENT (ID,TYPE) values (44,'secretaries');
Insert into MAHMOUD.DEPARTMENT (ID,TYPE) values (15,'doctor');
Insert into MAHMOUD.DEPARTMENT (ID,TYPE) values (222,'doctors');
Insert into MAHMOUD.DEPARTMENT (ID,TYPE) values (2,'doctors');
REM INSERTING into MAHMOUD.LOGIN
SET DEFINE OFF;
Insert into MAHMOUD.LOGIN (MAIL,PASSWORD) values ('labscientist','1312');
Insert into MAHMOUD.LOGIN (MAIL,PASSWORD) values ('provider','1312');
Insert into MAHMOUD.LOGIN (MAIL,PASSWORD) values ('admin','1312');
Insert into MAHMOUD.LOGIN (MAIL,PASSWORD) values ('doctor','1312');
Insert into MAHMOUD.LOGIN (MAIL,PASSWORD) values ('employee','1312');
REM INSERTING into MAHMOUD.MEDICALFILE
SET DEFINE OFF;
Insert into MAHMOUD.MEDICALFILE (ID,PRESSURE,LUNGS,BLOOD_TYPE,CHRONIC_DISEASES,ID_MRECORD) values (47,77,'o-','dd','ddd',null);
REM INSERTING into MAHMOUD.MEDICATIONS
SET DEFINE OFF;
REM INSERTING into MAHMOUD.PATIENT
SET DEFINE OFF;
Insert into MAHMOUD.PATIENT (ID,NAME,LAST_NAME,MAIL,AGE,GENDER,ID_PATIENT) values (44,'jkg','kfgykfyk','xtyjty',333,'Female',null);
REM INSERTING into MAHMOUD.PRESCRIPTION
SET DEFINE OFF;
REM INSERTING into MAHMOUD.RECRUITS
SET DEFINE OFF;
Insert into MAHMOUD.RECRUITS (ID,NAME,LAST_NAME,YEAR_OF_BIRTH,SEX,DEPARTMENT,ID_RECRUITS) values (1,'mahmoud','chebil','1999','Male','doctor',null);
Insert into MAHMOUD.RECRUITS (ID,NAME,LAST_NAME,YEAR_OF_BIRTH,SEX,DEPARTMENT,ID_RECRUITS) values (0,null,null,'0','Choose',null,null);
Insert into MAHMOUD.RECRUITS (ID,NAME,LAST_NAME,YEAR_OF_BIRTH,SEX,DEPARTMENT,ID_RECRUITS) values (44,'ahmed','kahri','2000','Male','doctor',null);
Insert into MAHMOUD.RECRUITS (ID,NAME,LAST_NAME,YEAR_OF_BIRTH,SEX,DEPARTMENT,ID_RECRUITS) values (2,'skander','laghmard','1997','Male','secretaries',null);
REM INSERTING into MAHMOUD.RESULTS
SET DEFINE OFF;
Insert into MAHMOUD.RESULTS (ID,TYPE,COVID19,ID_RESULTS) values (55,'ff','Positive',null);
Insert into MAHMOUD.RESULTS (ID,TYPE,COVID19,ID_RESULTS) values (14,'hlh','Negative',null);
Insert into MAHMOUD.RESULTS (ID,TYPE,COVID19,ID_RESULTS) values (15,'ddd','Negative',null);
Insert into MAHMOUD.RESULTS (ID,TYPE,COVID19,ID_RESULTS) values (77,'hlh','Negative',null);
REM INSERTING into MAHMOUD.TEST
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index APPOINTMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAHMOUD"."APPOINTMENT_PK" ON "MAHMOUD"."APPOINTMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CONSULTATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAHMOUD"."CONSULTATION_PK" ON "MAHMOUD"."CONSULTATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEPARTMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAHMOUD"."DEPARTMENT_PK" ON "MAHMOUD"."DEPARTMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEDICAL_RECORD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAHMOUD"."MEDICAL_RECORD_PK" ON "MAHMOUD"."MEDICALFILE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MEDICATIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAHMOUD"."MEDICATIONS_PK" ON "MAHMOUD"."MEDICATIONS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PATIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAHMOUD"."PATIENT_PK" ON "MAHMOUD"."PATIENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRESCREPTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAHMOUD"."PRESCREPTION_PK" ON "MAHMOUD"."PRESCRIPTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RECRUITS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAHMOUD"."RECRUITS_PK" ON "MAHMOUD"."RECRUITS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESULTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAHMOUD"."RESULTS_PK" ON "MAHMOUD"."RESULTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "MAHMOUD"."TEST_PK" ON "MAHMOUD"."TEST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table APPOINTMENT
--------------------------------------------------------

  ALTER TABLE "MAHMOUD"."APPOINTMENT" ADD CONSTRAINT "APPOINTMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAHMOUD"."APPOINTMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONSULTATION
--------------------------------------------------------

  ALTER TABLE "MAHMOUD"."CONSULTATION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MAHMOUD"."CONSULTATION" ADD CONSTRAINT "CONSULTATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "MAHMOUD"."DEPARTMENT" ADD CONSTRAINT "DEPARTMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOGIN
--------------------------------------------------------

  ALTER TABLE "MAHMOUD"."LOGIN" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "MAHMOUD"."LOGIN" MODIFY ("MAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDICALFILE
--------------------------------------------------------

  ALTER TABLE "MAHMOUD"."MEDICALFILE" ADD CONSTRAINT "MEDICAL_RECORD_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAHMOUD"."MEDICALFILE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEDICATIONS
--------------------------------------------------------

  ALTER TABLE "MAHMOUD"."MEDICATIONS" ADD CONSTRAINT "MEDICATIONS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAHMOUD"."MEDICATIONS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PATIENT
--------------------------------------------------------

  ALTER TABLE "MAHMOUD"."PATIENT" ADD CONSTRAINT "PATIENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAHMOUD"."PATIENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRESCRIPTION
--------------------------------------------------------

  ALTER TABLE "MAHMOUD"."PRESCRIPTION" ADD CONSTRAINT "PRESCREPTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAHMOUD"."PRESCRIPTION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECRUITS
--------------------------------------------------------

  ALTER TABLE "MAHMOUD"."RECRUITS" ADD CONSTRAINT "RECRUITS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAHMOUD"."RECRUITS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESULTS
--------------------------------------------------------

  ALTER TABLE "MAHMOUD"."RESULTS" ADD CONSTRAINT "RESULTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAHMOUD"."RESULTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEST
--------------------------------------------------------

  ALTER TABLE "MAHMOUD"."TEST" ADD CONSTRAINT "TEST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MAHMOUD"."TEST" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table APPOINTMENT
--------------------------------------------------------

  ALTER TABLE "MAHMOUD"."APPOINTMENT" ADD CONSTRAINT "APPOINTMENT_FK1" FOREIGN KEY ("ID_APPOINTMENT")
	  REFERENCES "MAHMOUD"."PATIENT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONSULTATION
--------------------------------------------------------

  ALTER TABLE "MAHMOUD"."CONSULTATION" ADD CONSTRAINT "CONSULTATION_FK1" FOREIGN KEY ("ID_CONSULTATION")
	  REFERENCES "MAHMOUD"."RECRUITS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEDICALFILE
--------------------------------------------------------

  ALTER TABLE "MAHMOUD"."MEDICALFILE" ADD CONSTRAINT "MEDICAL_RECORD_FK1" FOREIGN KEY ("ID_MRECORD")
	  REFERENCES "MAHMOUD"."PATIENT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEDICATIONS
--------------------------------------------------------

  ALTER TABLE "MAHMOUD"."MEDICATIONS" ADD CONSTRAINT "MEDICATIONS_FK1" FOREIGN KEY ("ID_MEDICATION")
	  REFERENCES "MAHMOUD"."PRESCRIPTION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PATIENT
--------------------------------------------------------

  ALTER TABLE "MAHMOUD"."PATIENT" ADD CONSTRAINT "PATIENT_FK1" FOREIGN KEY ("ID_PATIENT")
	  REFERENCES "MAHMOUD"."CONSULTATION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRESCRIPTION
--------------------------------------------------------

  ALTER TABLE "MAHMOUD"."PRESCRIPTION" ADD CONSTRAINT "PRESCREPTION_FK1" FOREIGN KEY ("ID_PRESCREPTION")
	  REFERENCES "MAHMOUD"."CONSULTATION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECRUITS
--------------------------------------------------------

  ALTER TABLE "MAHMOUD"."RECRUITS" ADD CONSTRAINT "RECRUITS_FK1" FOREIGN KEY ("ID_RECRUITS")
	  REFERENCES "MAHMOUD"."DEPARTMENT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESULTS
--------------------------------------------------------

  ALTER TABLE "MAHMOUD"."RESULTS" ADD CONSTRAINT "RESULTS_FK1" FOREIGN KEY ("ID_RESULTS")
	  REFERENCES "MAHMOUD"."TEST" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TEST
--------------------------------------------------------

  ALTER TABLE "MAHMOUD"."TEST" ADD CONSTRAINT "TEST_FK1" FOREIGN KEY ("ID_TEST")
	  REFERENCES "MAHMOUD"."PATIENT" ("ID") ENABLE;
